// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARbp7T7pE-6-pkfd6R2XYZD5l7fVirB5w',
    appId: '1:1013950263488:web:4f96de8faa7f74735cbd25',
    messagingSenderId: '1013950263488',
    projectId: 'whisper-guard',
    authDomain: 'whisper-guard.firebaseapp.com',
    storageBucket: 'whisper-guard.appspot.com',
    measurementId: 'G-8T1401TK8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE3wqvhTbAlOQ-1ncf2fa2ltErlXgfxZA',
    appId: '1:1013950263488:android:2281704a4f88baf85cbd25',
    messagingSenderId: '1013950263488',
    projectId: 'whisper-guard',
    storageBucket: 'whisper-guard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfd6KrDNIJTeV3JC6Cv7wBvYM_Irx4YH0',
    appId: '1:1013950263488:ios:e617332c8be5e4755cbd25',
    messagingSenderId: '1013950263488',
    projectId: 'whisper-guard',
    storageBucket: 'whisper-guard.appspot.com',
    iosBundleId: 'com.example.practiceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARbp7T7pE-6-pkfd6R2XYZD5l7fVirB5w',
    appId: '1:1013950263488:web:23b1fd598fded67e5cbd25',
    messagingSenderId: '1013950263488',
    projectId: 'whisper-guard',
    authDomain: 'whisper-guard.firebaseapp.com',
    storageBucket: 'whisper-guard.appspot.com',
    measurementId: 'G-4CLPNH5NXF',
  );
}
